#!/bin/bash
# Prompt customization
base_prompt='[$(date +%H:%M)]\[\033[01;32m\]\u@\h\[\033[00m\]:\[\033[01;34m\]\w\[\033[00m\]'

# Add Git branch information if available
if [ "$(type -t __git_ps1)" = "function" ]; then
	base_prompt="$base_prompt"'\[\033[33m\]$(__git_ps1)\[\033[00m\]'
fi

# Add trailing $ to prompt
PS1="$base_prompt"'\$ '
